container:
  #image: maven:latest
  image: openjdk:8-jdk

build_task:
  build_script: mvn clean compile test sonar:sonar
  on_failure:
    mail_script: mutt -s "Test Email" user@example.com < /dev/null


